name: MaintainableCSS - ein Ansatz um modulares, skalierbares und wartbares CSS zu schreiben | Von Adam Silver | Übersetzt ins Deutsche von Ronny Neefe
markdown: kramdown
url: http://maintainablecss.de
include: ['_pages']
collections:
  chapters:
    output: true
    permalink: /:collection/:title/
description: MaintainableCSS ist ein Ansatz um modulares, skalierbares und wartbares CSS zu schreiben.